apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mongodb-backup
  namespace: mongo
spec:
  schedule: "0 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mongodb-backup
            image: bitnami/mongodb:latest
            env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws_secret_access_key
            command:
            - /bin/sh
            - -c
            - >
              mongodump --host my-mongodb.mongo.svc.cluster.local --archive | aws s3 cp - s3://my-mongodb-backups/backup-$(date +\%Y-\%m-\%d).gz
          restartPolicy: OnFailure
